spring.application.name=job-search

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vacancies_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true